version: "3"

services:
  db:
    image: mysql:8
    env_file: ./.env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data/words_data.sql:/docker-entrypoint-initdb.d/words_data.sql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  # front:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_react
  #   restart: always
  #   volumes:
  #     - ./node:/front_code:cached
  #   command: sh -c "cd django_front && npm start"
  #   ports:
  #     - "3000:3000"
