version: "3"

services:
  db:
    image: mysql
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # データベースの文字コードを utf8mb4 に変更
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data/words_data.sql:/tmp/words_data.sql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  # front:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_react
  #   restart: always
  #   volumes:
  #     - ./node:/front_code:cached
  #   command: sh -c "cd django_front && npm start"
  #   ports:
  #     - "3000:3000"