# Generated by Django 4.1.5 on 2023-01-31 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('qid', models.AutoField(help_text='質問のID', primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=3, null=True)),
                ('stimulus_1', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_2', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_3', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_4', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_5', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='日付と時刻', null=True)),
                ('session_id', models.CharField(help_text='同ユーザーの異なる回のゲームを区別するためのID', max_length=14)),
                ('qid', models.IntegerField(blank=True, default=0, help_text='質問のID', null=True)),
                ('user_answer', models.CharField(blank=True, help_text='ユーザーの回答', max_length=20, null=True)),
                ('q_order', models.CharField(help_text='ユーザーに提示した刺激語の順', max_length=9, null=True)),
                ('u_order', models.CharField(help_text='ユーザーが役に立ったと思う刺激語の順', max_length=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
