# Generated by Django 4.1.3 on 2022-12-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('qid', models.AutoField(help_text='質問のID', primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_1', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_2', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_3', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_4', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_5', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
    ]
