# Generated by Django 4.1.3 on 2022-12-05 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('qid', models.AutoField(help_text='質問のID', primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_1', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_2', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_3', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_4', models.CharField(blank=True, max_length=20, null=True)),
                ('stimulus_5', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('datetime', models.DateTimeField(help_text='日付と時刻')),
                ('session_id', models.CharField(help_text='同ユーザーの異なる回のゲームを区別するためのID', max_length=14)),
                ('qid', models.AutoField(help_text='質問のID', primary_key=True, serialize=False)),
                ('user_answer', models.CharField(blank=True, help_text='ユーザーの回答', max_length=20, null=True)),
                ('u_stimulus_1', models.CharField(blank=True, help_text='1番目に役に立った刺激語', max_length=20, null=True)),
                ('u_stimulus_2', models.CharField(blank=True, help_text='2番目に役に立った刺激語', max_length=20, null=True)),
                ('u_stimulus_3', models.CharField(blank=True, help_text='3番目に役に立った刺激語', max_length=20, null=True)),
                ('u_stimulus_4', models.CharField(blank=True, help_text='4番目に役に立った刺激語', max_length=20, null=True)),
                ('u_stimulus_5', models.CharField(blank=True, help_text='5番目に役に立った刺激語', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
