# Generated by Django 4.1.5 on 2023-02-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='time',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='time_ms',
            field=models.IntegerField(help_text='解答にかかった時間 (ms)', null=True),
        ),
    ]
